"""Phase 4D entry point: build the three per-source auction join
tables (Treasury rates, CFTC TFF positioning, RTDSM macro vintages)
and audit them for row-count invariants, key uniqueness, and forbidden
(post-auction-result) columns.

Deliberately builds three separate tables, never a single combined
feature matrix (Phase 5). Run it via uv, from the repository root,
after every Phase 4A/4B/4C CLI has produced its processed tables:

    uv run python -m treasury_auction_stress.features.phase4d_audit_cli
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from treasury_auction_stress.features.phase4d_source_joins import (
    FORBIDDEN_RESULT_COLUMNS,
    audit_join_table,
    build_cftc_join_table,
    build_rates_join_table,
    build_rtdsm_join_table,
    build_samples,
)


def _df_to_markdown(df: pd.DataFrame) -> str:
    if df.empty:
        return "(none)"
    header = "| " + " | ".join(str(c) for c in df.columns) + " |"
    separator = "|" + "|".join(["---"] * len(df.columns)) + "|"
    rows = []
    for _, row in df.iterrows():
        cells = [str(v) if not (isinstance(v, list) and not v) else "(none)" for v in row]
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join([header, separator, *rows])


def run(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--processed-dir", default="data/processed", type=Path)
    parser.add_argument(
        "--reports-dir",
        default="artifacts",
        type=Path,
        help=(
            "Directory for generated reports/figures (default: the gitignored,"
            " intentionally-untracked local artifacts/ directory; created on"
            " demand)."
        ),
    )
    args = parser.parse_args(argv)

    nominal_df = pd.read_parquet(args.processed_dir / "treasury_auctions_nominal_coupons.parquet")
    normalized_complete_sample, ordinary_modeling_sample = build_samples(nominal_df)

    rates_wide = pd.read_parquet(args.processed_dir / "treasury_rates_wide.parquet")
    cftc_wide = pd.read_parquet(args.processed_dir / "cftc_positioning_wide.parquet")
    vintages_df = pd.read_parquet(args.processed_dir / "rtdsm_vintage_index.parquet")
    snapshots_df = pd.read_parquet(args.processed_dir / "rtdsm_snapshots.parquet")
    vintage_indices = {m: vintages_df[vintages_df["mnemonic"] == m].drop(columns="mnemonic") for m in vintages_df["mnemonic"].unique()}
    snapshots = {m: snapshots_df[snapshots_df["mnemonic"] == m].drop(columns="mnemonic") for m in snapshots_df["mnemonic"].unique()}

    audits = []
    args.processed_dir.mkdir(parents=True, exist_ok=True)
    for sample_name, sample_df, expected_rows in (
        ("ordinary_modeling_sample", ordinary_modeling_sample, len(ordinary_modeling_sample)),
        ("normalized_complete_sample", normalized_complete_sample, len(normalized_complete_sample)),
    ):
        rates_table = build_rates_join_table(sample_df, rates_wide)
        cftc_table = build_cftc_join_table(sample_df, cftc_wide)
        rtdsm_table = build_rtdsm_join_table(sample_df, vintage_indices, snapshots)

        rates_table.to_parquet(args.processed_dir / f"auction_join_treasury_rates_{sample_name}.parquet", index=False)
        cftc_table.to_parquet(args.processed_dir / f"auction_join_cftc_positioning_{sample_name}.parquet", index=False)
        rtdsm_table.to_parquet(args.processed_dir / f"auction_join_rtdsm_macro_{sample_name}.parquet", index=False)

        audits.append(audit_join_table(f"treasury_rates ({sample_name})", rates_table, expected_rows=expected_rows))
        audits.append(audit_join_table(f"cftc_positioning ({sample_name})", cftc_table, expected_rows=expected_rows))
        audits.append(audit_join_table(f"rtdsm_macro ({sample_name})", rtdsm_table, expected_rows=expected_rows))

    audit_df = pd.DataFrame(audits)
    all_passed = bool(audit_df["passed"].all())

    lines = [
        "# Phase 4D -- Source-Specific Auction Join Audit",
        "",
        ("Generated by `uv run python -m treasury_auction_stress.features.phase4d_audit_cli`. "
        "Builds three separate per-source join tables (Treasury rates, CFTC TFF positioning, RTDSM macro "
        "vintages), each for both sample universes and both prediction cutoffs -- **no combined feature "
        "matrix is constructed** (deferred to Phase 5)."),
        "",
        "## Row-count, uniqueness, and forbidden-column audit",
        "",
        _df_to_markdown(audit_df.drop(columns=["forbidden_columns_present"])),
        "",
        f"**Overall result: {'ALL PASSED' if all_passed else 'FAILURES DETECTED -- see below'}**",
        "",
        "## Forbidden-column check detail",
        "",
        (f"Checked against {len(FORBIDDEN_RESULT_COLUMNS)} known post-auction-result/outcome field names "
        "(yields, prices, accepted/tendered amounts by bidder category, allocation percentages, settlement-"
        "time accrued interest, the coupon rate itself, and targets.py's derived outcome fields). Each "
        "join table is built by selecting only `cusip`, `tenor`, `auction_date`, `announcemt_date`, "
        "`is_reopening`, both cutoff columns, and that source's own joined feature columns *before* any "
        "merge -- so no result column can leak in through the auction side of the join."),
        "",
    ]
    for row in audits:
        if row["forbidden_columns_present"]:
            lines.append(f"- **{row['table']}**: forbidden columns found: {row['forbidden_columns_present']}")
    if not any(row["forbidden_columns_present"] for row in audits):
        lines.append("- No forbidden columns found in any of the 6 join tables.")

    lines += [
        "",
        "## Uniqueness",
        "",
        "Each table's `(cusip, auction_date)` pair is checked for duplicates -- see the `duplicate_cusip_auction_date_rows` column above.",
    ]

    out_path = args.reports_dir / "phase_4d_source_join_audit.md"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path}")
    print(f"all_passed={all_passed}")
    return 0 if all_passed else 1


def main() -> None:
    raise SystemExit(run())


if __name__ == "__main__":
    main()
