"""Regression tests for the synthetic RTDSM-shaped fixture generator
(Phase 9 acceptance-review remediation, user decision 4). Proves:

- the two builder functions are deterministic (same bytes every call);
- the generated workbooks are schema-equivalent to RTDSM's real format
  (parseable by the real parser, expected vintage/period structure);
- no committed file, tracked path, or generated bytes contains any of
  the specific real values the two removed fixtures used to carry.
"""

from __future__ import annotations

import io

import openpyxl
import pandas as pd
from rtdsm_synthetic_fixtures import (
    _SYNTHETIC_MARKER,
    build_ipt_synthetic_workbook,
    build_ruc_synthetic_workbook,
)

from treasury_auction_stress.data.rtdsm_normalize import parse_workbook
from treasury_auction_stress.data.rtdsm_schema import VARIABLE_BY_MNEMONIC

# The exact real values the removed fixtures carried (from the prior,
# now-deleted tests/fixtures/rtdsm_{ruc,ipt}_sample.xlsx and the test
# assertions that read them) -- used ONLY as a negative-match list here,
# never written to any fixture or generator.
_REMOVED_REAL_RUC_VALUES = {14.7, 14.8, 4.3}
_REMOVED_REAL_IPT_VALUE = 91.3


def test_ruc_builder_is_byte_deterministic():
    assert build_ruc_synthetic_workbook() == build_ruc_synthetic_workbook()


def test_ipt_builder_is_byte_deterministic():
    assert build_ipt_synthetic_workbook() == build_ipt_synthetic_workbook()


def test_ruc_workbook_parses_with_the_real_parser_and_expected_shape():
    long_df, anomalies = parse_workbook(build_ruc_synthetic_workbook(), VARIABLE_BY_MNEMONIC["RUC"])
    assert anomalies == {
        "unrecognized_vintage_columns": [],
        "unparseable_observation_periods": 0,
        "observation_period_gaps": 0,
    }
    assert set(long_df["vintage_label"]) == {"20Q2", "21Q1", "25Q4", "26Q1", "26Q3"}
    assert long_df["observation_date"].min() == pd.Timestamp("2019-06-01")
    assert long_df["observation_date"].max() == pd.Timestamp("2026-07-01")


def test_ipt_workbook_parses_with_the_real_parser_and_expected_shape():
    long_df, anomalies = parse_workbook(build_ipt_synthetic_workbook(), VARIABLE_BY_MNEMONIC["IPT"])
    assert anomalies == {
        "unrecognized_vintage_columns": [],
        "unparseable_observation_periods": 0,
        "observation_period_gaps": 0,
    }
    assert set(long_df["vintage_label"]) == {"20M3", "20M6", "26M7", "26M8"}


def test_no_removed_real_value_appears_in_the_synthetic_ruc_values():
    long_df, _ = parse_workbook(build_ruc_synthetic_workbook(), VARIABLE_BY_MNEMONIC["RUC"])
    present_values = set(long_df["value"].dropna().round(1))
    assert not (present_values & _REMOVED_REAL_RUC_VALUES)


def test_no_removed_real_value_appears_in_the_synthetic_ipt_values():
    long_df, _ = parse_workbook(build_ipt_synthetic_workbook(), VARIABLE_BY_MNEMONIC["IPT"])
    present_values = set(long_df["value"].dropna().round(1))
    assert _REMOVED_REAL_IPT_VALUE not in present_values


def test_workbook_metadata_discloses_synthetic_origin():
    for builder in (build_ruc_synthetic_workbook, build_ipt_synthetic_workbook):
        wb = openpyxl.load_workbook(io.BytesIO(builder()))
        assert wb.properties.title == _SYNTHETIC_MARKER
        assert "SYNTHETIC" in wb.properties.title.upper()
