from __future__ import annotations

import json
import subprocess
from pathlib import Path

from treasury_auction_stress.governance.audit_cli import _load_allowlist_fingerprints
from treasury_auction_stress.governance.release_audit import (
    _fingerprint,
    allowlist_token,
    audit_tree,
    check_dashboard_json_safe,
    find_large_tracked_files,
    is_publishable_path,
    scan_for_identifying_info,
    scan_for_secret_patterns,
)

REPO_ROOT = Path(__file__).resolve().parents[1]

# All credential-shaped strings below are unmistakably fake test
# fixtures -- never a real secret. They are deliberately implausible
# (literal "FAKE" substrings, sequential digits) so they cannot be
# mistaken for or reused as a working credential.
FAKE_ENV_FILE = (
    "FRED_API_KEY=FAKE1234567890abcdefFAKE1234\n"
    "DATABASE_PASSWORD='not-a-real-password-fixture'\n"
)
FAKE_AWS_KEY = "AKIAFAKEFAKEFAKEFAKE"
FAKE_HISTORICAL_FIXTURE_TEXT = (
    "# old debug notes\n"
    "api_key = 'sk-FAKE1234567890ABCDEFAKE'\n"
    "print('ready')\n"
)
# A deliberately-fake development-tool session URL on the reserved
# `.invalid` top-level domain (RFC 2606) -- it can never resolve to any
# real service, and its id is sequential hex.
FAKE_SESSION_URL_LINE = (
    "see https://example.invalid/code/session_0123456789abcdef for context\n"
)


def test_synthetic_env_file_is_rejected_by_path_allowlist():
    assert is_publishable_path(".env") is False
    assert is_publishable_path("config/.env.production") is False


def test_synthetic_env_file_content_is_flagged_by_secret_scan():
    findings = scan_for_secret_patterns(FAKE_ENV_FILE, location=".env")
    categories = {f.category for f in findings}
    assert "secret:fred_api_key_env" in categories
    assert "secret:generic_assignment" in categories
    # never assert on / embed the actual matched value
    for f in findings:
        assert "FAKE1234567890" not in f.description


def test_fake_key_in_historical_fixture_text_is_detected_without_exposing_value():
    findings = scan_for_secret_patterns(
        FAKE_HISTORICAL_FIXTURE_TEXT, location="historical_fixture.py"
    )
    assert len(findings) == 1
    assert findings[0].category == "secret:generic_assignment"
    assert "sk-FAKE1234567890ABCDEFAKE" not in findings[0].description


def test_raw_and_processed_parquet_or_db_paths_are_rejected():
    # Any real (non-placeholder) file under data/raw|interim|processed is
    # bulk data and must be rejected regardless of its extension.
    assert is_publishable_path("data/raw/treasury_auctions_raw_2020.json") is False
    assert is_publishable_path("data/processed/phase_7_point_predictions.parquet") is False
    assert is_publishable_path("data/interim/scratch.db") is False
    assert is_publishable_path("data/raw/dump.sqlite3") is False


def test_gitkeep_and_small_text_fixtures_are_not_false_positives():
    assert is_publishable_path("data/raw/.gitkeep") is True
    assert is_publishable_path("data/interim/.gitkeep") is True
    assert is_publishable_path("data/processed/.gitkeep") is True
    assert is_publishable_path("tests/fixtures/small_auction_sample.json") is True


def test_xlsx_under_fixtures_is_rejected_after_rtdsm_remediation():
    """Second acceptance-review remediation (user decision 4): the real
    RTDSM .xlsx fixtures were removed and replaced with synthetic,
    Python-generated bytes (tests/rtdsm_synthetic_fixtures.py) -- no
    .xlsx fixture should exist under tests/fixtures/ anymore, and the
    format allowlist no longer carries the earlier disclosed exception
    for it. Defense in depth: reject any .xlsx that might reappear."""
    assert is_publishable_path("tests/fixtures/rtdsm_ipt_sample.xlsx") is False
    assert is_publishable_path("tests/fixtures/anything.xlsx") is False


def test_tests_fixtures_gets_no_blanket_exemption():
    """Regression guard for the Phase 9 acceptance-review finding that
    `is_publishable_path` returned True for ANY path under
    tests/fixtures/ before running any rejection check. Every category
    below must remain rejected even placed under tests/fixtures/ --
    being in that directory must never be sufficient on its own.
    """
    assert is_publishable_path("tests/fixtures/.env") is False
    assert is_publishable_path("tests/fixtures/.env.production") is False
    assert is_publishable_path("tests/fixtures/private_key.pem") is False
    assert is_publishable_path("tests/fixtures/cert.crt") is False
    assert is_publishable_path("tests/fixtures/client.p12") is False
    assert is_publishable_path("tests/fixtures/scratch.db") is False
    assert is_publishable_path("tests/fixtures/scratch.sqlite3") is False
    assert is_publishable_path("tests/fixtures/model.pkl") is False
    assert is_publishable_path("tests/fixtures/model.joblib") is False
    assert is_publishable_path("tests/fixtures/model.onnx") is False
    assert is_publishable_path("tests/fixtures/bundle.zip") is False
    assert is_publishable_path("tests/fixtures/bundle.tar.gz") is False
    assert is_publishable_path("tests/fixtures/__pycache__/x.pyc") is False
    assert is_publishable_path("tests/fixtures/tool.exe") is False
    assert is_publishable_path("tests/fixtures/tool.dylib") is False
    # No extension at all -- not on the narrow fixture format allowlist,
    # so an "unexpected binary" with no suffix is rejected too.
    assert is_publishable_path("tests/fixtures/mystery_binary") is False
    # Bulk/processed formats stay rejected under fixtures/ exactly as
    # they are anywhere else in the tree.
    assert is_publishable_path("tests/fixtures/dealer_stats/sample.parquet") is False
    assert is_publishable_path("tests/fixtures/dump.h5") is False


def test_oversized_fixture_is_rejected_even_with_a_publishable_suffix():
    from treasury_auction_stress.governance.release_audit import (
        is_publishable_fixture_size,
    )

    assert is_publishable_fixture_size("tests/fixtures/small.json", 1_000) is True
    assert (
        is_publishable_fixture_size("tests/fixtures/unexpectedly_huge.json", 5_000_000)
        is False
    )
    # Same size, but outside tests/fixtures/: the fixture cap doesn't apply
    # (general large-file reporting is find_large_tracked_files' job).
    assert is_publishable_fixture_size("dashboard/data/large.json", 5_000_000) is True


def test_credential_shaped_content_under_fixtures_still_fails_content_scan():
    """A path that passes is_publishable_path (an allowed fixture format)
    must still be caught by the content scan if it contains secret-shaped
    text -- the path allowlist and content scan are independent checks."""
    result = audit_tree(
        [
            (
                "tests/fixtures/leaky_config.yml",
                f"api_key: '{FAKE_AWS_KEY}'\n",
            )
        ]
    )
    assert result.passed is False
    assert any(f.category == "secret:aws_access_key" for f in result.findings)


def test_real_committed_dashboard_json_passes_safety_check():
    repo_root = Path(__file__).resolve().parents[1]
    dashboard_json_path = repo_root / "dashboard" / "data" / "phase8_dashboard_data.json"
    with dashboard_json_path.open() as f:
        data = json.load(f)
    findings = check_dashboard_json_safe(data)
    assert findings == []


def test_absolute_home_path_and_dev_session_url_are_flagged():
    text = (
        "ran from /Users/exampleuser/Projects/repo/.venv/bin/python3\n"
        + FAKE_SESSION_URL_LINE
    )
    findings = scan_for_identifying_info(text, location="notes.md")
    categories = {f.category for f in findings}
    assert "identifying_info:absolute_home_path" in categories
    assert "identifying_info:dev_session_url" in categories


def test_session_url_detected_regardless_of_domain_or_tld():
    """The session-URL detector is domain-agnostic: it keys on the
    '<host>/code/session_<id>' shape, not on any specific vendor domain
    or top-level domain, so an arbitrary or newly-registered domain
    cannot bypass it. Sample values are assembled from parts so this
    test file itself contains only the one reviewed literal canary
    (FAKE_SESSION_URL_LINE)."""
    hosts = [
        "example.invalid",
        "tool.example.com",
        "internal-host.example.org",
        "sub.host.example.net",
        "short.io",
    ]
    for host in hosts:
        text = "trace at https://" + host + "/code/" + "session_" + "abc012DEF\n"
        findings = scan_for_identifying_info(text, location="notes.md")
        flagged = [
            f for f in findings if f.category == "identifying_info:dev_session_url"
        ]
        assert flagged, f"session URL on host {host!r} was not detected"
        assert all(f.severity == "hard_block" for f in flagged)

    # A bare hostless mention must NOT trip the detector -- ordinary
    # prose about sessions stays legal.
    benign = scan_for_identifying_info(
        "the session_id column is documented here\n", location="notes.md"
    )
    assert not any(
        f.category == "identifying_info:dev_session_url" for f in benign
    )


def test_allowlisted_session_canary_is_path_and_fingerprint_specific():
    """An allowlist entry permits one exact value at one exact path
    only. The reviewed canary passes at its approved path; the SAME
    canary value at any other path still hard-blocks, and a DIFFERENT
    session value at the approved path still hard-blocks."""
    fp = next(
        f.fingerprint
        for f in scan_for_identifying_info(FAKE_SESSION_URL_LINE)
        if f.category == "identifying_info:dev_session_url"
    )
    approved_entry = allowlist_token("tests/test_release_audit.py", fp)

    at_approved_path = audit_tree(
        [("tests/test_release_audit.py", FAKE_SESSION_URL_LINE)],
        allowed_identifying_info=frozenset({approved_entry}),
    )
    assert at_approved_path.passed is True

    same_canary_other_path = audit_tree(
        [("docs/notes.md", FAKE_SESSION_URL_LINE)],
        allowed_identifying_info=frozenset({approved_entry}),
    )
    assert same_canary_other_path.passed is False

    different_value_approved_path = audit_tree(
        [
            (
                "tests/test_release_audit.py",
                "see https://example.invalid/code/" + "session_" + "fedcba987654\n",
            )
        ],
        allowed_identifying_info=frozenset({approved_entry}),
    )
    assert different_value_approved_path.passed is False


def test_find_large_tracked_files_reports_oversized_entries(tmp_path):
    big_file = tmp_path / "big.bin"
    big_file.write_bytes(b"0" * 2_000_000)
    small_file = tmp_path / "small.txt"
    small_file.write_text("tiny")

    result = find_large_tracked_files(
        ["big.bin", "small.txt"], root=tmp_path, threshold_bytes=1_000_000
    )
    assert result == [("big.bin", 2_000_000)]


def test_find_large_tracked_files_empty_on_repo_dashboard_json_alone():
    repo_root = Path(__file__).resolve().parents[1]
    result = find_large_tracked_files(
        ["dashboard/data/phase8_dashboard_data.json"],
        root=repo_root,
        threshold_bytes=50_000_000,
    )
    assert result == []


def test_audit_tree_passes_on_clean_synthetic_fileset():
    result = audit_tree(
        [
            ("README.md", "# Project\nNo secrets here.\n"),
            ("tests/fixtures/sample.json", '{"tenor": "10-Year"}'),
            ("data/raw/.gitkeep", ""),
        ]
    )
    assert result.passed is True


def test_no_currently_tracked_text_file_contains_an_absolute_home_path():
    """Regression guard for the Phase 9 finding that an early committed
    working-log report embedded a real local
    /Users/<username>/... path. Scans every git-tracked file in the
    current working tree, not just that one file, so the same defect
    class is caught anywhere it recurs, not just at its original site.

    Applies the same reviewed fingerprint allowlist audit_cli.py uses
    (configs/governance_audit_allowlist.yml): a handful of tracked files
    legitimately match this pattern on purpose -- documentation prose
    describing the pattern abstractly, and this project's own
    deliberately-fake canary test fixtures -- each individually
    reviewed there, never exempted by path or category.
    """
    tracked = subprocess.run(
        ["git", "ls-files"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.splitlines()

    allowed = _load_allowlist_fingerprints(REPO_ROOT)
    offenders: list[str] = []
    for rel_path in tracked:
        full_path = REPO_ROOT / rel_path
        if not full_path.is_file():
            continue
        try:
            text = full_path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue  # binary or unreadable; not a text-leak candidate
        findings = [
            f
            for f in scan_for_identifying_info(text, location=rel_path)
            if f.category == "identifying_info:absolute_home_path"
            and allowlist_token(rel_path, f.fingerprint) not in allowed
        ]
        if findings:
            offenders.append(rel_path)

    assert offenders == [], f"absolute local path found in: {offenders}"


def test_audit_tree_fails_on_intentionally_leaky_synthetic_fixture():
    result = audit_tree(
        [
            ("README.md", "# Project\n"),
            (
                ".env",
                f"AWS_ACCESS_KEY_ID={FAKE_AWS_KEY}\n",
            ),
            ("data/processed/phase_7_point_predictions.parquet", "not really parquet bytes"),
        ]
    )
    assert result.passed is False
    categories = {f.category for f in result.findings}
    assert "rejected_path" in categories
    assert "secret:aws_access_key" in categories


# --- Acceptance-review remediation: findings 3, 4, 5 ------------------
#
# A distinctive, unmistakably-fake "canary" value used only to prove it
# never appears in output -- never a real secret/PII value.
CANARY_EMAIL = "definitely-not-a-real-person-9f8e7d@example-canary.test"
CANARY_HOME_PATH = "/Users/definitely_not_a_real_username_9f8e7d/Projects/x"


def test_identifying_info_scan_never_embeds_the_matched_value():
    """Finding 3: the previous implementation's scan_for_identifying_info
    put the raw regex match straight into Finding.description. Assert the
    canary value never appears in any finding's description, category, or
    location -- only a redacted note and a fingerprint.
    """
    text = f"contact: {CANARY_EMAIL}\nran from {CANARY_HOME_PATH}/.venv/bin/python3\n"
    findings = scan_for_identifying_info(text, location="notes.md")
    assert len(findings) >= 2
    for f in findings:
        assert CANARY_EMAIL not in f.description
        assert CANARY_EMAIL not in f.category
        assert CANARY_EMAIL not in f.location
        assert CANARY_HOME_PATH not in f.description
        assert CANARY_HOME_PATH not in f.category
        assert CANARY_HOME_PATH not in f.location
        # every identifying-info finding carries a non-reversible
        # fingerprint instead of the value itself
        assert f.fingerprint is not None
        assert f.fingerprint.startswith("fp:")
        assert CANARY_EMAIL not in f.fingerprint
        assert CANARY_HOME_PATH not in f.fingerprint


def test_identifying_info_never_leaks_through_check_dashboard_json_safe():
    """Same canary guarantee through the recursive JSON-safety checker,
    which delegates to scan_for_identifying_info -- exercised separately
    since it builds its own child_path strings from dict keys/values.
    """
    findings = check_dashboard_json_safe({"note": f"see {CANARY_EMAIL}"})
    assert findings
    for f in findings:
        assert CANARY_EMAIL not in f.description
        assert CANARY_EMAIL not in f.location


def test_identifying_info_never_leaks_via_an_unusual_location_string():
    """Finding 3 extends beyond the ordinary happy path: an unusual
    (very long) `location` argument must not change the no-leak
    guarantee on the returned findings."""
    text = f"token holder: {CANARY_EMAIL}"
    findings = scan_for_identifying_info(text, location="x" * 10_000)
    assert findings
    for f in findings:
        assert CANARY_EMAIL not in f.description
        assert CANARY_EMAIL not in f.location


def test_fingerprint_is_deterministic_and_never_reveals_the_value():
    fp1 = _fingerprint(CANARY_EMAIL)
    fp2 = _fingerprint(CANARY_EMAIL)
    assert fp1 == fp2  # same value -> same fingerprint, for dedup/allowlisting
    assert CANARY_EMAIL not in fp1
    assert fp1 != _fingerprint("a-completely-different-value@example.test")


# --- Finding 4: identifying-info severity/disposition policy ----------


def test_hard_block_identifying_info_fails_audit_tree_by_default():
    """Finding 4: audit_tree() used to collect identifying-info findings
    without ever failing the audit on them. A hard-blocking category
    (home path, email, development-tool session URL) must now fail the audit even
    when no `secret:*` pattern and no rejected path are present.
    """
    result = audit_tree([("notes.md", f"contact: {CANARY_EMAIL}\n")])
    assert result.passed is False
    assert any(f.severity == "hard_block" for f in result.findings)


def test_review_severity_identifying_info_does_not_fail_audit_tree():
    """A lower-confidence category (bare IPv4) is collected but does not
    by itself block -- it's `review`, not `hard_block`."""
    result = audit_tree([("notes.md", "server: 10.0.0.5\n")])
    assert result.passed is True
    categories = {f.category for f in result.findings}
    assert "identifying_info:ipv4_address" in categories
    review_findings = [f for f in result.findings if f.category == "identifying_info:ipv4_address"]
    assert all(f.severity == "review" for f in review_findings)


def test_consent_to_publish_identifying_info_is_never_inferred():
    """Never infer consent from mere presence: the SAME email finding
    must still hard-block the audit even when it appears in a file whose
    path/name suggests intentional public attribution (e.g. a project
    "authors" line) -- only an explicit fingerprint allowlist can permit
    a specific value, never a filename/path heuristic."""
    result = audit_tree(
        [
            (
                "pyproject.toml",
                f'authors = [{{ name = "Someone", email = "{CANARY_EMAIL}" }}]\n',
            )
        ]
    )
    assert result.passed is False


def test_explicit_fingerprint_allowlist_can_permit_one_specific_value():
    """The only sanctioned way to stop a hard-blocking identifying-info
    finding from failing the audit: the caller explicitly lists that
    exact value's fingerprint. A DIFFERENT value's finding is unaffected."""
    findings = scan_for_identifying_info(f"contact: {CANARY_EMAIL}\n", location="x")
    fp = findings[0].fingerprint
    assert fp is not None

    blocked = audit_tree([("notes.md", f"contact: {CANARY_EMAIL}\n")])
    assert blocked.passed is False

    allowed = audit_tree(
        [("notes.md", f"contact: {CANARY_EMAIL}\n")],
        allowed_identifying_info=frozenset({allowlist_token("notes.md", fp)}),
    )
    assert allowed.passed is True

    still_blocked = audit_tree(
        [("notes.md", "contact: someone-else@example.test\n")],
        allowed_identifying_info=frozenset({allowlist_token("notes.md", fp)}),
    )
    assert still_blocked.passed is False


def test_an_unrelated_fingerprint_never_accidentally_allowlists_a_secret():
    """A wrong/unrelated fingerprint in the allowlist must not permit a
    secret finding -- the allowlist only ever matches the EXACT value's
    own fingerprint, never anything else."""
    result = audit_tree(
        [(".env", f"AWS_ACCESS_KEY_ID={FAKE_AWS_KEY}\n")],
        allowed_identifying_info=frozenset({"anything"}),
    )
    assert result.passed is False


def test_rejected_path_can_never_be_allowlisted_via_fingerprint():
    """rejected_path findings have no fingerprint (fingerprint=None) and
    are never affected by allowed_identifying_info -- there is no value
    to individually review for a path-based rejection."""
    result = audit_tree(
        [("data/raw/dump.parquet", "not really parquet bytes")],
        allowed_identifying_info=frozenset({"anything"}),
    )
    assert result.passed is False


def test_a_secret_finding_can_be_allowlisted_by_its_own_correct_fingerprint():
    """Secret findings DO now carry a fingerprint (deliberately-fake test
    canaries in this project's own test suite need a reviewed way to
    stop failing the current-tree public-release audit -- see
    configs/governance_audit_allowlist.yml). The allowlist still only
    ever matches the exact value's own fingerprint, proven here the same
    way as the identifying-info allowlist test above. Uses a publishable
    path (not .env) so a rejected_path finding can't mask the result.
    """
    findings = scan_for_secret_patterns(f"AWS_ACCESS_KEY_ID={FAKE_AWS_KEY}\n", location="x")
    fp = findings[0].fingerprint
    assert fp is not None

    blocked = audit_tree([("config.py", f"AWS_ACCESS_KEY_ID={FAKE_AWS_KEY}\n")])
    assert blocked.passed is False

    allowed = audit_tree(
        [("config.py", f"AWS_ACCESS_KEY_ID={FAKE_AWS_KEY}\n")],
        allowed_identifying_info=frozenset({allowlist_token("config.py", fp)}),
    )
    assert allowed.passed is True


# --- Second acceptance-review remediation (public-history/identity/
# license decisions): current-tree audit must pass end-to-end now that
# the private email is removed, and must fail again if either the email
# or a local home path is reintroduced. ---


def _current_tracked_paths_and_contents() -> list[tuple[str, str]]:
    """Every path that would be tracked after `git add -A` -- i.e. the
    real current working-tree state, not the stale index. `git ls-files`
    alone still lists a path deleted-on-disk-but-not-yet-staged (exactly
    the case for the two removed real RTDSM fixtures right now), which
    would make this a false negative for "is anything unsafe currently
    on disk." `git ls-files --others --exclude-standard` adds new,
    not-yet-staged, not-gitignored files.
    """
    tracked = subprocess.run(
        ["git", "ls-files"], cwd=REPO_ROOT, capture_output=True, text=True, check=True
    ).stdout.splitlines()
    untracked = subprocess.run(
        ["git", "ls-files", "--others", "--exclude-standard"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.splitlines()
    all_paths = sorted(set(tracked) | set(untracked))
    out = []
    for rel_path in all_paths:
        full_path = REPO_ROOT / rel_path
        if not full_path.is_file():
            continue  # deleted-but-still-indexed; not actually on disk
        try:
            text = full_path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            text = ""
        out.append((rel_path, text))
    return out


def test_current_repository_tree_passes_the_full_audit():
    """End-to-end regression guard: the actual current proposed public
    tree (not a synthetic fileset), scanned with the same reviewed
    allowlist audit_cli.py applies (configs/governance_audit_allowlist.yml
    -- every entry there is this project's own deliberately-fake test
    canary or benign doc prose, individually reviewed; see that file),
    must pass audit_tree() with `passed is True`. Note `result.findings`
    still LISTS every hard_block-severity match regardless of the
    allowlist (only `passed` reflects the allowlist decision) -- see
    tests/test_governance_audit_allowlist.py for a check that every
    *unallowlisted* hard_block finding is specifically accounted for.
    If this ever regresses to `passed is False`, either something
    sensitive was reintroduced into a tracked file, or a new test canary
    needs a new reviewed allowlist entry.
    """
    allowed = _load_allowlist_fingerprints(REPO_ROOT)
    result = audit_tree(_current_tracked_paths_and_contents(), allowed_identifying_info=allowed)
    assert result.passed is True


def test_a_private_email_reintroduced_into_pyproject_toml_would_fail_the_audit():
    """Regression guard for the exact defect this review removed: if a
    real-shaped email address were ever reintroduced into pyproject.toml
    (or any other tracked file), the current-tree audit must fail, never
    silently pass because the file is a project-metadata/authors file."""
    content = 'authors = [{ name = "Nathan Yang", email = "someone@example.test" }]\n'
    result = audit_tree([("pyproject.toml", content)])
    assert result.passed is False
    assert any(f.category == "identifying_info:email_address" for f in result.findings)


def test_a_local_home_path_reintroduced_into_any_file_would_fail_the_audit():
    """Regression guard: a local /Users/... or /home/... path in any
    tracked file must fail the audit -- proven generically, not only for
    the one file this review fixed."""
    content = "ran from /Users/exampleuser/Projects/repo/.venv/bin/python3\n"
    result = audit_tree([("reports/some_future_report.md", content)])
    assert result.passed is False
    assert any(f.category == "identifying_info:absolute_home_path" for f in result.findings)


def test_license_file_is_present_publishable_and_has_the_chosen_copyright_line():
    license_path = REPO_ROOT / "LICENSE"
    assert license_path.exists()
    text = license_path.read_text(encoding="utf-8")
    assert "MIT License" in text
    assert "Copyright (c) 2026 Nathan Yang" in text
    assert is_publishable_path("LICENSE") is True
    # the LICENSE file itself must never trip the audit
    result = audit_tree([("LICENSE", text)])
    assert result.passed is True
