"""Command-line entry point for Phase 1: download, normalize, and
report on the Treasury auctions dataset.

Run it via uv, from the repository root:

    uv run python -m treasury_auction_stress.data.cli

See README.md for what this does and where its outputs go.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from treasury_auction_stress.data.client import TreasuryApiError
from treasury_auction_stress.data.download import download_auctions
from treasury_auction_stress.data.normalize import (
    check_schema_drift,
    nominal_coupon_subset,
    normalize_auctions,
    pages_to_records,
    to_raw_dataframe,
)
from treasury_auction_stress.data.quality import (
    build_quality_report,
    render_quality_report_markdown,
)
from treasury_auction_stress.data.raw_store import load_raw_payload
from treasury_auction_stress.data.time_utils import market_today_date

DEFAULT_START_DATE = "2010-01-01"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Download (or reuse a cached copy of) the official Treasury "
            "Fiscal Data auctions dataset, normalize it, and regenerate "
            "the data-quality report."
        )
    )
    parser.add_argument(
        "--start-date",
        default=DEFAULT_START_DATE,
        help=f"Auction date range start, YYYY-MM-DD (default: {DEFAULT_START_DATE}).",
    )
    parser.add_argument(
        "--end-date",
        default=None,
        help=(
            "Auction date range end, YYYY-MM-DD (default: today in "
            "America/New_York -- the U.S. Treasury auction market's own "
            "timezone, deliberately not UTC; see "
            "treasury_auction_stress.data.time_utils)."
        ),
    )
    parser.add_argument("--raw-dir", default="data/raw", type=Path)
    parser.add_argument("--processed-dir", default="data/processed", type=Path)
    parser.add_argument(
        "--reports-dir",
        default="artifacts",
        type=Path,
        help=(
            "Directory for generated reports/figures (default: the gitignored,"
            " intentionally-untracked local artifacts/ directory; created on"
            " demand)."
        ),
    )
    parser.add_argument(
        "--force-refresh",
        action="store_true",
        help="Re-download even if a cached raw artifact for today (UTC retrieval date) already exists.",
    )
    return parser.parse_args(argv)


def run(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    end_date = args.end_date or market_today_date()

    print(
        f"Downloading Treasury auctions from {args.start_date} to {end_date} "
        "(auction_date upper bound, America/New_York calendar date) ..."
    )
    try:
        result = download_auctions(
            start_date=args.start_date,
            end_date=end_date,
            raw_dir=args.raw_dir,
            force_refresh=args.force_refresh,
        )
    except TreasuryApiError as exc:
        print(f"ERROR: could not reach the Treasury Fiscal Data API: {exc}", file=sys.stderr)
        print(
            "No fabricated or substitute data will be produced. "
            "See docs/point_in_time_rules.md for the no-substitution policy.",
            file=sys.stderr,
        )
        return 1

    cache_note = "reused cached artifact from" if result.was_cached else "downloaded fresh artifact for"
    print(f"OK: {cache_note} retrieval date {result.retrieval_date} (UTC calendar date)")
    print(f"  raw file: {result.raw_path}")
    print(f"  rows: {result.metadata.row_count}")

    payload = load_raw_payload(result.raw_path)
    records = pages_to_records(payload)
    raw_df = to_raw_dataframe(records)
    schema_drift = check_schema_drift(raw_df)

    normalized_df, anomalies = normalize_auctions(raw_df)
    nominal_df = nominal_coupon_subset(normalized_df)

    args.processed_dir.mkdir(parents=True, exist_ok=True)
    full_path = args.processed_dir / "treasury_auctions_full.parquet"
    nominal_path = args.processed_dir / "treasury_auctions_nominal_coupons.parquet"
    normalized_df.to_parquet(full_path, index=False)
    nominal_df.to_parquet(nominal_path, index=False)
    print(f"  wrote processed table: {full_path} ({len(normalized_df)} rows)")
    print(f"  wrote nominal-coupon subset: {nominal_path} ({len(nominal_df)} rows)")

    report = build_quality_report(normalized_df, anomalies, schema_drift)
    generated_note = (
        f"Generated by `uv run python -m treasury_auction_stress.data.cli` "
        f"against data retrieved {result.retrieval_date} (UTC calendar date), "
        f"covering auction dates {args.start_date} to {end_date} "
        "(America/New_York calendar date -- the Treasury auction market's own "
        "timezone; see treasury_auction_stress.data.time_utils)."
    )
    markdown = render_quality_report_markdown(report, generated_note)
    args.reports_dir.mkdir(parents=True, exist_ok=True)
    quality_report_path = args.reports_dir / "auction_data_quality.md"
    quality_report_path.write_text(markdown, encoding="utf-8")
    print(f"  wrote data-quality report: {quality_report_path}")

    return 0


def main() -> None:
    raise SystemExit(run())


if __name__ == "__main__":
    main()
